import { default as NavBar, default as ResponsiveAppBar } from '@/components/NavBar.js';
import { app } from '@/firebase.js';
import styles from '@/styles/Home.module.css';
import { getAuth } from 'firebase/auth';
import { Inter } from 'next/font/google';
import Head from 'next/head';
import Image from 'next/image';

export default function Home() {
  // chat with AI
  async function onSubmit(event) {
    event.preventDefault();
    const response = await fetch('api/openai',{
      method: "POST",
      headers: {
        "Content-Type":"applications/json",
      },
      body: JSON.stringify({prompt: event.target.prompt.value}),
    })
    // of type {"completion": "..."}
    const data = await response.json();
    // TODO: display data.completion
    console.log(data);
  }

  // auth  control
  const auth = getAuth(app);
  console.log(auth);
  return (
    <>
      <Head>
        <title>TheraPal</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ResponsiveAppBar />

        {auth.currentUser ? (
          <div>You're Signed In!</div>
        ) : (
          <div>Please Sign up!</div>
        )}

      </main>
    </>
  );
}
