import styles from '@/styles/Home.module.css';
import { Inter } from 'next/font/google';
import Head from 'next/head';
import Image from 'next/image';
import { OpenAI } from './api/openai.js';
import { getAuth } from 'firebase/auth';
import { app } from '@/firebase.js';
import NavBar from '@/components/NavBar.js';
import ResponsiveAppBar from '@/components/NavBar.js';

export default function Home() {
  const auth = getAuth(app);
  console.log(auth);
  return (
    <>
      <Head>
        <title>TheraPal</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ResponsiveAppBar />

        {auth.currentUser ? (
          <div>You're Signed In!</div>
        ) : (
          <div>Please Sign up!</div>
        )}
      </main>
    </>
  );
}
