import Link from 'next/link';

import {
  GoogleAuthProvider,
  getAuth,
  signInWithPopup,
  signOut,
} from 'firebase/auth';
import { app } from '../firebase';
import { getFirestore, doc, setDoc } from '@firebase/firestore';
import { useRouter } from 'next/router';
import Head from 'next/head';
import ResponsiveAppBar from '@/components/NavBar';
import { Box, Button } from '@mui/material';

const provider = new GoogleAuthProvider();

const auth = getAuth(app);
auth.languageCode = 'it';

provider.setCustomParameters({
  login_hint: 'user@example.com',
});

const styles = {
  container: {
    backgroundImage: `url(${'background.jpeg'})`,
    backgroundSize: '100vw',
    backgroundSize: 'cover',
    backgroundRepeat: 'no-repeat',

    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    flexGrow: 1,
  },
};

const db = getFirestore(app);

const Login = () => {
  const handleSignIn = () => {
    signInWithPopup(auth, provider).then((userCred) => {
      console.log(userCred);
      const userData = {
        name: userCred.user.displayName,
        email: userCred.user.email,
        photo: userCred.user.photoURL,
      };
      setDoc(doc(db, 'users', userCred.user.uid), userData, {
        merge: true,
      }).then(() => {
        router.push('/');
      });
    });
  };

  const router = useRouter();

  return (
    <>
      <Head>
        <title>TheraPal</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ResponsiveAppBar />
        <Box sx={styles.container}>
          <Button sx={{ background: 'white' }} onClick={handleSignIn}>
            Login With Google
          </Button>
        </Box>
      </main>
    </>
  );
};

export default Login;
